declare module "*.svg";
declare module "*.scss";
declare module "*.png";
declare module "*.webp";
declare module "*.jpg";
declare module "*.jpeg";
declare module "*.gif";
declare module "*.bmp";
declare module "*.tiff";
